name: 'Pandemonium '
favicon: null
layout_spectrum: 0.998
typography_spectrum: 0.5187571158166975
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#040404'
    - '#ee2c24'
    - '#a7a2a3'
    - '#373737'
  brandStrength: 0.5
  lightness: 0.06630156980827451
  saturation: 0.4557498716749251
  rhythmicContrast: 0.18193330010399222
purpose: []
